name: Test-Integration

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      working-directory: go/src/github.com/tendermint/starport

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: "Get Go 1.15"	
        run: |	
          go get golang.org/dl/go1.15	
          go1.15 download	

      - name: Install protoc
        uses: arduino/setup-protoc@v1

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.working-directory }}
          fetch-depth: 0

      - name: Build UI
        working-directory: ${{ env.working-directory }}
        run: make ui

      - name: Install Starport
        working-directory: ${{ env.working-directory }}
        run: |
          go install ./...

      - name: Run Integration Tests
        working-directory: ${{ env.working-directory }}
        run: ./scripts/test-integration 
        env:
          GONAME: "go1.15"
